import os
import pathlib
import re

WIKI_DIR = "/Users/elena/Documents/llm_wiki/llm wiki/wiki"

def get_frontmatter(content):
    match = re.search(r'---(.*?)---', content, re.DOTALL)
    if not match:
        return {}
    
    fm_text = match.group(1)
    fm = {}
    for line in fm_text.strip().split('\n'):
        if ':' in line:
            key, val = line.split(':', 1)
            fm[key.strip()] = val.strip()
    return fm

def generate_index():
    wiki_path = pathlib.Path(WIKI_DIR)
    files = list(wiki_path.glob("*.md"))
    
    categories = {
        "Programs & Pricing": [],
        "Locations & Schedule": [],
        "Customer Inquiries": [],
        "Operations": [],
        "Uncategorized": []
    }
    
    for file_path in files:
        if file_path.name in ["index.md", "log.md"]:
            continue
            
        content = file_path.read_text()
        fm = get_frontmatter(content)
        title = file_path.stem.replace('-', ' ').title()
        
        # Simple heuristic for categorization
        filename = file_path.name
        if any(word in filename for word in ['pricing', 'program', 'camp', 'club']):
            categories["Programs & Pricing"].append((title, file_path.name))
        elif any(word in filename for word in ['location', 'court', 'spot']):
            categories["Locations & Schedule"].append((title, file_path.name))
        elif any(word in filename for word in ['question', 'inquiry', 'join', 'ready']):
            categories["Customer Inquiries"].append((title, file_path.name))
        elif any(word in filename for word in ['parent', 'child']):
            categories["Operations"].append((title, file_path.name))
        else:
            categories["Uncategorized"].append((title, file_path.name))
            
    index_content = """# Tennis Academy Knowledge Base

> This wiki is an automated extraction of knowledge from institutional communications, processed via LLM for synthesis and anonymized for privacy.

## 🧠 Project Architecture
- **Input**: Raw email data (Gmail exports).
- **Processing**: Python pipeline using LangChain & Gemini Pro.
- **Privacy**: Multi-stage anonymization (Regex + LLM).
- **Output**: Structured Obsidian-ready Markdown.

---

## 📂 Knowledge Repository

"""
    
    for cat, items in categories.items():
        if not items:
            continue
        index_content += f"### {cat}\n"
        for title, filename in sorted(items):
            index_content += f"- [[{filename[:-3]} | {title}]]\n"
        index_content += "\n"
        
    index_content += """---
*Generated by the LLM Wiki Exporter*
"""
    
    (wiki_path / "index.md").write_text(index_content)
    print("New index.md generated.")

if __name__ == "__main__":
    generate_index()
